### PR TITLE
Update openssl version

### PR DESCRIPTION
**Pull request by cbenhagen**

### CODE REVIEW

**Comment by cbenhagen** [comment]
Oops I might have been too quick. I am getting build-errors with this version.

**Comment by rnixx** [comment]
Me too, but prior versions of openssl always get invisible as soon as there is a newer version. Thus it's not very reliable depending on the official download links. Any suggestion where to download instead?

**Comment by rnixx** [comment]
Just seen old releases are archived e.g. at

    https://www.openssl.org/source/old/1.0.2/openssl-1.0.2f.tar.gz

Actually this makes it not much better. There could be a version-to-URL mapping dict in __init__ for solving this problem... ?

**Comment by cbenhagen** [comment]
Version 1.0.2h builds without errors.

**Comment by Zen-CODE** [comment]
1.0.2h works for me too. Thanks

**Pull request merged**
