### PR TITLE
Fix host setuptools

### PR DESCRIPTION
**Pull request by rnixx**

### CODE REVIEW

**Comment by rnixx** [comment]
It seems that installing a package dependent on setuptools only works the first time after setuptools is installed to hostpython, all subsequent calls exit with an error. After manually extracting setuptools egg in hostpython site-packages, the error was gone

**Comment by rnixx** [comment]
setuptools egg now gets extracted in hostpython site-packages and .pth mappings are removed in order to avoid errors with subsequent setuptools based package installations with hostpython.

**Comment by Zen-CODE** [comment]
This may solve a lot of errors we've seen with hostpython during the builds. Will try and test shortly.

Thanks.

**Comment by Zen-CODE** [comment]
Great stuff. Works like a charm. Thanks :-)

**Pull request merged**
