### PR TITLE
Fix jinja2 recipe, remove from broken list

### PR DESCRIPTION
**Pull request by Zen-CODE**

### CODE REVIEW

**Comment by Zen-CODE** [comment]
I think distutils is gone now, so that should hopefully not be an issue :-)

**Comment by AndreMiras** [comment]
Yes but I actually think the issue was that it did depend on it still and probably that line:
```
        shprint(cmd, "-i", "", "s/setuptools/distutils.core/g", "./setup.py", _env=build_env)
```
Was there to rely on `setuptools` instead.
Also I would advise on not using `jinja==master` but pin to the last release to have reproducible builds over time, what do you think?

**Comment by Zen-CODE** [comment]
Re:It might have, but it does not now? Or am I missing you here?
Re: master vs. fixed version. Yes, I also prefer version pinning. But it does come at the (slight by comparison) cost of maintenance. Still, agreed it's better. 

May I suggest merging this (if that's the only issue). Then I'll lock the version once we I get to the flask recipe. That's really the one I'm honing in on, and that version will dictate the version for quite a few - werkzeug, jinja2, markupsafe etc. Makes sense to lock them all at the version preferred by flask?

**Comment by AndreMiras** [comment]
I'm 100% for merging if the build is green. If the build is not green I'm also happy to merge but only by leaving the recipe to the broken list. That list goal is to keep track of broken recipe for the CI perspective.
Regarding the version pinning yes that could definitely be addressed in another PR. But one thing, it's not that restrictive because people can still install the version they want (at least in p4a it's this way). The only thing it says is, some day a developer AND the CI made got it working (at least at build time). Then later people can always explicitly bump the default version with a PR if they want, but then the action is clearly logged/verified as non regression

**Comment by Zen-CODE** [comment]
All passed! :-)

**Pull request merged**
