### PR TITLE
Add bitcode support

### PR DESCRIPTION
**Pull request by kewlbear**
Thank you for this great project!
I have implemented bitcode support.
Touchtracer example successfully archived with bitcode.
Please take a look.

### CODE REVIEW

**Review by misl6 — COMMENTED** [review]
Thank you for your appreciation!

Considering that the developer still has the master switch to opt off from bitcode submission on XCode, I don't see any threat but only positive things about embedding bitcode where there's a chance to do it.

Do you just mind changing the related line of documentation into our README.md file?

**Comment by kewlbear** [comment]
Thank you for your quick feedback!

Is it okay to just remove the entry stating bitcode is not supported?  Or
do you have any suggested change?

2021년 4월 5일 (월) 오후 5:28, Mirko ***@***.***>님이 작성:

**Comment by misl6** [comment]
I think We can change it with a disclaimer, maybe something that says BITCODE is now partially supported, and which recipes are now supported.

**Comment by kewlbear** [comment]
@misl6  I have updated README like you suggested.  Do you think it's okay, or want to change something?

**Comment by misl6** [comment]
Sorry for being slow on this one, but I just wanted to interview a core dev about why **bitcode** was previously defined as not supported.

Seems there's nothing that could lock us to merge your PR. I tested it and analyzed via `otool` and looks good.

Thank you!

**Review by misl6 — APPROVED** [review]

**Comment by kewlbear** [comment]
Thank you @misl6 !

**Pull request merged**
