### PR TITLE
Update python loader to load from frameworks as well as main exe (i.e…

### PR DESCRIPTION
**Pull request by zscgeek**
Add support for embedding kivy in a dynamic framework. This allows us to correctly load the python modules from the sub dl instead of the main exe

### CODE REVIEW

**Comment by Zen-CODE** [comment]
Please read this. https://blog.kivy.org/2012/03/ios-support-for-kivy/

It seems there may be a political/Apple restriction around this. It would clearly be better, but iOS as a target is really important....

**Comment by zscgeek** [comment]
Hi there!

Apple changed many of the rules with ios8+ around dynamic loading of libraries and you now are allowed to have dynamic frameworks in your iOS app. That being said there are still things you run into from time to time getting past the runtime and code checks but the hard limit is no longer there.

The one limitation that is still there, is if you have dynamic framework, you can't dynamically load sub frameworks. It all has to be flattened (ie no Frameworks/myCoolstuff.Framework/Frameworks/mySubLibrary.framework). 

Anyway, this patch allows us to create a Framework that has the kivy runtime for python and be called from the main app. As we have some python dependencies in our SDK we ship to app developers, we need this patch to correctly work. Once upon a time all the static stuff was needed, but that does not seem to be the case anymore. 

    RJ

**Comment by Zen-CODE** [comment]
Seems to work without issues, so I' happy to merge it. Struggled to find docs re: RTLD_SELF and RTLD_MAIN_ONLY. What effect will this have current behavior? Can we be sure it won't break anything?

**Comment by zscgeek** [comment]
Take a look at https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/dlsym.3.html 

the TLDR; is that RTLD_MAIN_ONLY will ONLY search the main executable for the named symbol, while RTLD_SELF will search inside the currently loaded library, and then start a search using the standard model to find  a match. 

With the RTLD_SELF change, the kivy library and python libraries can be located inside a sub-framework.

**Comment by Zen-CODE** [comment]
That's great. A useful extension. Thanks :-)

**Pull request merged**
