### PR TITLE
Support For zbarcam

### PR DESCRIPTION
**Pull request by GoBig87**
I've been merging multiple fixes, applying some of my own fixes and adding new recipes in order to support 2D and 1D bar code scanning with zbarcam and make it fully cross platform with the inclusion of iOS support.  I've attached of zip file of my branch (maybe it would be better to do a diff and include all of my file changes?) but running this branch following these steps should get you a working zbar scanner that will work with android and ios

add
requirements = hostpython,kivy,python,futures,requests,pycrypto,openssl,host_setuptools,pil,zbarlight,pyobjus,numpy
and garden reqs = xcamera, zbarcam to the spec file

Run buildozer ios debug
It will fail, cd .buildozer/ios/platform/kivy-ios
Delete everything, replace with my kivy-ios branch
run ./toochain build hostpython
cd back project level and run buildozer ios debug
numpy fails to download properly download manually and place  in kivy-ios/.cache folder
and use ./toolchain.py to build
build manually with toolchain.py
Add your team ID in the general->signing tab
add libc++,libsqlite3,libbz2,libz,libiconv.2
disable bit code
run buildozer ios debug

[Kivy-ios-zbar_branch.zip](https://github.com/kivy/kivy-ios/files/2108667/Kivy-ios-zbar_branch.zip)

I still need to incorporate autofocus and forcing orientation for iOS cameras but it will capture 2D bar codes as is right now.

### CODE REVIEW

**Comment by AndreMiras** [comment]
Thak you @GoBig87 , but I think you missed something. That pull request is to merge `kivy_1.10.0` to `master` rather than your own fork with your recipe fixes., right? I was expecting to see some `libzbar` recipe and that kind of things. But I don't even see your fork.

**Comment by AndreMiras** [comment]
I've just joined IRC `#kivy-dev` on Freenode if you need assistance. I may not stay that long there today.

**Comment by GoBig87** [comment]
Alright I've got a fork made on my page at https://github.com/GoBig87/Zbarcam_Kivy-ios

**Comment by AndreMiras** [comment]
Good start. You've done the hardest part fixing the recipes. Take your time understanding how git and Github works and make a pull request. I could probably make one with what you gave now, but you deserve the credits.
So clone your fork, create a branch, apply your changes and make it. Also think about fixing your `git config user.email` and `git config user.name`.

**Comment by GoBig87** [comment]
Alright I've been coding for about 15 hours straight.   I need a break,  I'll fix it first thing tomorrow morning.

**Comment by AndreMiras** [comment]
1. clone your fork
`git clone git@github.com:GoBig87/kivy-ios.git`

2. clone the side project you just shared with all the changes
`git clone https://github.com/GoBig87/Zbarcam_Kivy-ios.git`

3. cd to your fork and create a branch
`cd kivy-ios && git checkout -b zbarlight_support`

4. apply the changes from the other clone
`cp -r Zbarcam_Kivy-ios/* .`

5. review your changes
`git status`

Result:
```
On branch zbarlight_support
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   README.rst
        modified:   recipes/ffmpeg/__init__.py
        modified:   recipes/freetype/__init__.py
        modified:   recipes/host_setuptools/__init__.py
        modified:   recipes/hostlibffi/__init__.py
        modified:   recipes/hostpython/__init__.py
        modified:   recipes/ios/src/ios.pyx
        modified:   recipes/ios/src/ios_browser.m
        modified:   recipes/ios/src/ios_wrapper.h
        modified:   recipes/kivy/__init__.py
        modified:   recipes/libffi/__init__.py
        modified:   recipes/libjpeg/__init__.py
        modified:   recipes/libpng/__init__.py
        modified:   recipes/numpy/__init__.py
        modified:   recipes/openssl/__init__.py
        modified:   recipes/pil/__init__.py
        modified:   recipes/pil/pil_setup.patch
        modified:   recipes/pkgresources/__init__.py
        modified:   recipes/python/__init__.py
        modified:   recipes/python/posixmodule.patch
        modified:   recipes/sdl2/__init__.py
        modified:   recipes/sdl2_image/__init__.py
        modified:   recipes/sdl2_mixer/__init__.py
        modified:   toolchain.py
        modified:   tools/biglink
        modified:   tools/cythonize.py
        modified:   tools/external/xcassets.py
        modified:   tools/templates/{{ cookiecutter.project_name }}-ios/main.m

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        recipes/kivy/kivy-0.10-ios-camera.patch
        recipes/libiconv/
        recipes/libzbar/
        recipes/opencv/
        recipes/pkgresources/pkgr/
        recipes/zbar/
        recipes/zbarlight/

no changes added to commit (use "git add" and/or "git commit -a")
```

6. ouch! now clean the mess :)
So this is the result of all the other branches you previously merged.
But like I said your pull request should be as clean/light as possible. So basically the obvious ones are `recipes/libzbar/` and`recipes/zbarlight/` to be tracked (`git add`). And the rest, I'm not sure it's 100% relevant for that pull request, for example `openssl` should probably not be in, right? Sometimes even if other pull requests are relevant for you, but were not merged for a reason. Don't merge it as part of your pull request. Simply give some hint to the maintainer saying something like "this zbarlight pull request depends on #whatever-other-not-yet-merged-pull-request". But we cannot sneak other unmerged pull request in our. If other are not yet merged it's usually for a reason.

Again take your time to do it and dare to ask for support on IRC since you're contributing. Or clone my repository and drop me an email if you don't want to spam this ticket with git questions.

**Comment by GoBig87** [comment]
I've made a proper pull request with #291 .  Changes can be found there.  A working branch for getting the camera and zbar running can be located here https://github.com/GoBig87/Zbarcam_Kivy-ios.

**Comment by AndreMiras** [comment]
That's way better well done. You can close that current ticket and I'll help reviewing the other one.

**Pull request closed without merging**
