### PR TITLE
Updated sdl2, sdl2_image, sdl2_mixer, sdl2_ttf, kivy

### PR DESCRIPTION
**Pull request by misl6**
This PR updates:

- sdl2 2.0.8 --> 2.0.9
- sdl2_image 2.0.0 --> 2.0.4
- sdl2_mixer 2.0.0 --> 2.0.4
- sdl2_ttf 2.0.12 --> 2.0.14
- kivy 1.10.1 --> current master (via hash)

### CODE REVIEW

**Comment by hackalog** [comment]
Why the hardcoding to a particular current master?

**Comment by misl6** [comment]
@hackalog, we used to do the same on p4a.

I think that targeting `master` is something wrong, cause could create potential (untested) problems to users.

Also, considering that We're next to a new release, i think that we need to start abandoning v1.10.1 (at least on master) in order to get ready for the next release of `kivy` on `kivy-ios`.

**Comment by hackalog** [comment]
I also think targeting master (or a particular hash) is wrong. If I'm to understand, this is supposed to be updated to rely on 1.11 when it is released?

Because otherwise, I'd expect to rely either on a named version, or 'master'

**Comment by misl6** [comment]
@hackalog , You're right, the PR is supposed to be updated to rely on 1.11 when released.

When upgrading kivy to a newer version, in order to fix some bugs that were present in my `kivy-ios` packaged app I've find out that `sdl2_image` was needed to be upgraded. (Current `kivy` master relies on `sdl2_image==2.0.4` ).

All the other improvements to the sdl2-related part aren't specifically needed, but I think that it's a good practice to keep them updated.

**Comment by tito** [comment]
Tested, works, but requires CodeMedia and CoreVideo now. Templates must be adjusted too.

**Pull request merged**
