### PR TITLE
[WIP] Netifaces

### PR DESCRIPTION
**Pull request by cbenhagen**
@rnixx and @Zen-CODE what exactly were the problems solved by 7cca790? With this commit I was unable to install netifaces. I had some setuptools troubles too which I solved with [this](https://github.com/cbenhagen/kivy-ios/blob/785634ff0f2bd1e6021c1de3183dd2fe33774e09/recipes/netifaces/__init__.py#L27-L30). I am not quite happy with that solution either. Any suggestions?

### CODE REVIEW

**Comment by akshayaurora** [comment]
@cbenhagen @rnixx same issues for pil, I had to comment out the changes to get pil installation to work again.2

**Comment by rnixx** [comment]
@cbenhagen Without unpacking setuptools and removing the pth linking, I got errors when trying to install other recipes via hostpython depending on setuptools, like https://github.com/rnixx/kivy-ios/blob/twisted_recipe/recipes/txaio/__init__.py

For some reason the pth file was not resolved properly. On the other hand I am wondering why an extracted setuptools causes problems in your case. Did you run host_setuptools recipe on an existing hostpython or a fresh installation?

**Comment by cbenhagen** [comment]
Is this the error you get?

```python
  File "/Users/ben/Projects/couch-kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1287, in install_site_py
    with io.open(sitepy) as strm:
TypeError: bad argument type for built-in operation
```

Full log here: https://gist.github.com/cbenhagen/d2d5024716f26fd8e7101dec47bb7ac4

**Comment by cbenhagen** [comment]
I ran this on an existing hostpython. But this should not matter at all and if it does we should open an issue for this.

**Comment by cbenhagen** [comment]
Running your six recipe with subprocess works however:
```python
from os.path import join
from toolchain import PythonRecipe
from toolchain import shprint
import os
import sh
import subprocess


class SixRecipe(PythonRecipe):
    version = "1.10.0"
    url = (
        "https://pypi.python.org/packages/b3/b2/"
        "238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/"
        "six-{version}.tar.gz"
    )
    depends = ["python"]

    def install(self):
        arch = list(self.filtered_archs)[0]
        build_dir = self.get_build_dir(arch.arch)
        os.chdir(build_dir)
        hostpython = sh.Command(self.ctx.hostpython)
        build_env = arch.get_env()
        dest_dir = join(self.ctx.dist_dir, "root", "python")
        pythonpath = join(dest_dir, 'lib', 'python2.7', 'site-packages')
        build_env['PYTHONPATH'] = pythonpath

        # args = [hostpython, "setup.py", "install", "--prefix", dest_dir]
        # shprint(*args, _env=build_env)

        env = ' '.join(['{}="{}"'.format(k, v) for k, v in build_env.iteritems()])
        cmd = ' '.join([env, self.ctx.hostpython, "setup.py", "install", "--prefix", dest_dir])
        out = subprocess.check_output(cmd, shell=True)
        print(out)

recipe = SixRecipe()
```

I wonder what the usage of the sh library has to do with it.

**Comment by rnixx** [comment]
@cbenhagen 

> Is this the error you get?
> ...
> TypeError: bad argument type for built-in operation

Yes. I stepped into the code with ``pdb`` and ``sitepy`` was ``None``. Totally weird. https://github.com/pypa/setuptools/blob/master/setuptools/command/easy_install.py#L1280 ``sitepy`` is a path and also checked whether it exists https://github.com/pypa/setuptools/blob/master/setuptools/command/easy_install.py#L1285, but suddenly ``None``... !?

Interesting that the use of ``sh`` lib seems to cause the problem. What's the benefit over using ``subprocess`` directly? Maybe it should be dropped?

**Comment by cbenhagen** [comment]
Setting `sitepy` to `None` would raise `TypeError: invalid file: None`. Weird indeed.

`sh` is just a more pythonic way to use shell commands. While it could just be dropped I would prefer to understand what is going on.

**Pull request closed without merging**
