### PR TITLE
Cleanup + Add test in CI for cookiecutter related things

### PR DESCRIPTION
**Pull request by misl6**
- Removed (and added to requirements.txt file) the un-needed things in `tools/external`
- Added a CI test case for cookiecutter related things.

### CODE REVIEW

**Comment by AndreMiras** [comment]
Yes xcassette was maintained, see for instance: f288af58d53afda8fd53dec4fb16a065b25b4ded and f8916b95f55b9c00414707a0ef958da505034f9b
So I would say let's not delete this one as it seems kivy-ios custom.
Also we should start unit testing it if we're about to maintain that

**Comment by tshirtman** [comment]
maybe it could have been a PR against https://github.com/albert-zhang/gen_xcassets

**Comment by AndreMiras** [comment]
I have really little clue about macOS so I can't tell. But the code base doesn't look the same so at least it wasn't heavily borrowed from there. I would say to keep it simple for now I would simply undelete the `tools/external/xcassets.py` file. And then definitely if there's a way to use existing maintained/tested thirdparty dependency I would say we should go for it via separate PR

**Comment by tshirtman** [comment]
true, maybe it's not the correct one, i agree it's simpler to keep this one for now.

**Comment by AndreMiras** [comment]
misl6 just gave me a heads up on Discord and didn't actually delete it :sweat_smile: 
So I'm good for a merge after another one can take a look

**Comment by Zen-CODE** [comment]
On checking out the branch:

    richard@Richards-MacBook-Pro kivy-ios % python3 toolchain.py build kivy python openssl                         
    Traceback (most recent call last):
        File "toolchain.py", line 40, in <module>
        import sh
        ModuleNotFoundError: No module named 'sh'

**Comment by Zen-CODE** [comment]
So. I'm guessing we need to install those requirements. One issue I have with that is that I've been unable to run the toolchain successfully in a venv. I can only get a successful build the python version installed via brew. So depending on libraries in the native python install is...a pity.

It would also mean we would need to change installation instructions.

**Comment by Zen-CODE** [comment]
Even when creating a venv, I get [this err](https://gist.github.com/Zen-CODE/6f39f49082e7c806f58ec5ec12e1f200). I think there was a reason that these external tools where included in the repo..

**Comment by AndreMiras** [comment]
The `sh` requirement is defined already https://github.com/kivy/kivy-ios/pull/454/files#diff-b4ef698db8ca845e5845c4618278f29aR5 
Until we fix the `venv` we can still install the requirements with the `--user` flag.
You're talking about this issue right? https://github.com/kivy/kivy-ios/issues/401
I have some ideas to dig into and I'm confident I could fix, but I need to install macOS first

**Comment by Zen-CODE** [comment]
@AndreMiras I know it's added to requirements. Please see my comments above. But as I mentioned, the issues is:
* it then needs to be installed into the system python (venv not working)
* the installation instructions need to be updated to specify that.

To be honest, I'd rather live with the ugliness of external/tools that depending on requirements being installed to the systems python. I'd only be happy if a venv could be used....

**Comment by AndreMiras** [comment]
OK let's keep this pending until we fix the venv then

**Comment by AndreMiras** [comment]
@misl6 could you rebase as https://github.com/kivy/kivy-ios/pull/462 got merged?

**Comment by AndreMiras** [comment]
So far so good, here's what I've done to test it.
I've dropped all my pip dependencies installed outside the venv to test it:
```
deactivate
pip3 uninstall --yes $(pip3 freeze)
```
Then I've created a completely new venv to build recipes:
```
rm -rf venv/ && python3 -m venv venv 
. venv/bin/activate
pip install -r requirements.txt
pip install cython==0.28.1
python toolchain.py build python3 kivy
```
It built successfully. I'm now about to try on device and merge if it works OK

**Pull request merged**
