### PR TITLE
New recipe for libpng

### PR DESCRIPTION
**Pull request by filipefigcorreia**
This is a recipe to build libpng. This is a first step towards creating a recipe for matplotlib (see #208).

### CODE REVIEW

**Comment by mrhdias** [comment]
The recipe don't download the archive.
If I try download the archive manually, this url "http://vorboss.dl.sourceforge.net/project/libpng/libpng16/1.6.24/libpng-1.6.24.tar.gz" redirect to "https://sourceforge.net/projects/libpng/files/"

```
...
Extract libpng
Extract libpng for i386
Traceback (most recent call last):
  File "./toolchain.py", line 1311, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1082, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1106, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 974, in build_recipes
    recipe.execute()
  File "/Users/prrcarvalho/Development/kivy-ios-master/toolchain.py", line 585, in execute
    self.extract()
  File "/Users/prrcarvalho/Development/kivy-ios-master/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/prrcarvalho/Development/kivy-ios-master/toolchain.py", line 621, in extract
    self.extract_arch(arch.arch)
  File "/Users/prrcarvalho/Development/kivy-ios-master/toolchain.py", line 625, in extract_arch
    dest_dir = join(build_dir, self.archive_root)
  File "/Users/prrcarvalho/Development/kivy-ios-master/toolchain.py", line 577, in archive_root
    value = self.get_archive_rootdir(self.archive_fn)
  File "/Users/prrcarvalho/Development/kivy-ios-master/toolchain.py", line 442, in get_archive_rootdir
    archive = tarfile.open(filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1673, in open
    return func(name, "r", fileobj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/Users/prrcarvalho/Development/kivy-ios-master/.cache/libpng-libpng-1.6.24.tar.gz'
```

**Comment by mrhdias** [comment]
This work

```
# -*- coding: utf-8 -*-
from toolchain import Recipe, shprint
from os.path import join
import sh, os

class PngRecipe(Recipe):
    version = '1.6.26'
    url = 'http://netcologne.dl.sourceforge.net/project/libpng/libpng16/{version}/libpng-{version}.tar.gz'
    depends = ["python"]
    library = '.libs/libpng16.a'

    def build_arch(self, arch):
        build_env = arch.get_env()
        configure = sh.Command(join(self.build_dir, "configure"))
        shprint(configure,
                "CC={}".format(build_env["CC"]),
                "LD={}".format(build_env["LD"]),
                "CFLAGS={}".format(build_env["CFLAGS"]),
                "LDFLAGS={}".format(build_env["LDFLAGS"]),
                "--prefix=/",
                "--host={}".format(arch.triple),
                "--disable-shared",
                "--enable-maintainer-mode")
        shprint(sh.make, "clean")
        shprint(sh.make, _env=build_env)

recipe = PngRecipe()
```

**Comment by filipefigcorreia** [comment]
I'm unable to test this right now, but if you can please try with the URL: `http://downloads.sourceforge.net/sourceforge/libpng/libpng-1.6.26.tar.gz`.
It should also work, and doesn't depend on a particular sourceforge mirror.

**Comment by mrhdias** [comment]
It work fine now :-)
Thanks

**Comment by Zen-CODE** [comment]
Thanks :-)

**Pull request merged**
