### PR TITLE
Fixing compilation problems on osx 10.12 with xcode 9.

### PR DESCRIPTION
**Pull request by tonibagur**
*Important Note:
When the xcode project is created, in order to get kivy working you have to manually add the following framewors:
- CoreMotion
- libz
- libsqlite3

### CODE REVIEW

**Comment by mbrockman1** [comment]
This is still failing for me when trying to run '/toolchain.py build kivy'. Here is the total [output](https://gist.githubusercontent.com/mbrockman1/7cb7a11a71d5d73cf7b9e78e6b9d78b0/raw/1bd8147f6c774975532b44dbc1b7cdc1e7d63b5e/gistfile1.txt)

**Comment by sastels** [comment]
Very happy someone else is working on this, thanks!! :)
1) When I pull down your branch I can build python, etc successfully with toolchain
2) My python/kivy project builds successfully with toolchain
3) when I try to build the project with Xcode I get linking errors from sdl_mixer that are fixed by adding -lc++ to "Other Linking Flags" as described in https://github.com/fullstackreact/react-native-firestack/issues/59
4) When I run the project on my phone, it starts and crashes when importing kivy.app, with the line
```
 ImportError: dynamic module does not define init function (init_clock)
```

Full output:
```
2017-10-12 11:23:22.662616-0400 kasuku_stories_16[3501:1829636] [DYMTLInitPlatform] platform initialization successful
2017-10-12 11:23:22.745919-0400 kasuku_stories_16[3501:1829430] [Accessibility] ****************** Loading GAX Client Bundle ****************
2017-10-12 11:23:22.819813-0400 kasuku_stories_16[3501:1829430] +[CATransaction synchronize] called within transaction
2017-10-12 11:23:23.059158-0400 kasuku_stories_16[3501:1829430] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight
2017-10-12 11:23:23.059257-0400 kasuku_stories_16[3501:1829430] PythonHome is: /var/containers/Bundle/Application/FF57831B-803E-43F7-BF32-0B1DC4685B59/kasuku_stories_16.app
2017-10-12 11:23:23.060086-0400 kasuku_stories_16[3501:1829430] Initializing python
2017-10-12 11:23:23.128549-0400 kasuku_stories_16[3501:1829430] Running main.pyo: /var/containers/Bundle/Application/FF57831B-803E-43F7-BF32-0B1DC4685B59/kasuku_stories_16.app/YourApp/main.pyo
[INFO   ] [Logger      ] Record log in /private/var/mobile/Containers/Data/Application/42FBD880-88EC-4096-A364-FA5DFE414BA4/Documents/.kivy/logs/kivy_17-10-12_0.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.1 (r271:86832, Oct 12 2017, 10:12:49) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
 Traceback (most recent call last):
   File "/Users/sastels/LearnLeapFly/git/branch_release_15_on_ios/glexp_kasuku/kasuku_stories_16-ios/YourApp/main.py", line 25, in <module>
   File "/Users/sastels/LearnLeapFly/git/kivy-ios/build/kivy/i386/kivy-1.10.0/iosbuild/lib/python2.7/site-packages/kivy/app.py", line 319, in <module>
   File "/Users/sastels/LearnLeapFly/git/kivy-ios/build/kivy/i386/kivy-1.10.0/iosbuild/lib/python2.7/site-packages/kivy/base.py", line 29, in <module>
   File "/Users/sastels/LearnLeapFly/git/kivy-ios/build/kivy/i386/kivy-1.10.0/iosbuild/lib/python2.7/site-packages/kivy/clock.py", line 362, in <module>
   File "<string>", line 33, in load_module
 ImportError: dynamic module does not define init function (init_clock)
2017-10-12 11:23:23.212891-0400 kasuku_stories_16[3501:1829430] Application quit abnormally!
2017-10-12 11:23:23.219588-0400 kasuku_stories_16[3501:1829430] Leaving
```

**Comment by mbrockman1** [comment]
@sastels Can you explain step by step on how you manually add frameworks? I am really struggling here to make it work.

**Comment by sastels** [comment]
@mbrockman1 I'm not sure why you're getting those `'endian.h' file not found` errors. I didn't have those problems. I built the toolchain recipes and my Xcode project without errors. The frameworks / libraries were added to my Xcode project via Build Phases / Link Binary With Libraries as described in https://stackoverflow.com/questions/3352664/how-to-add-existing-frameworks-in-xcode-4

More explicitly, to build kivy-ios I ran
```
git clone https://github.com/tonibagur/kivy-ios.git
cd kivy-ios && git checkout xcode9_osx10_12
./toolchain.py distclean
./toolchain.py build openssl kivy
```
This ran without errors, and `toolchain.py status` reported that things had built successfully. Mind you, I've brew/apt/pip installed who knows what on my system. At the very least you should ensure that you've carefully installed all the Requirements from https://github.com/kivy/kivy-ios, and your Xcode and command line tools are all updated.

**Comment by mbrockman1** [comment]
@sastels I am really sorry to be a pain, but I uninstalled all my brew packages and reinstalled just the dependencies. I am using Cython 0.23, Xcode 9, macOS 10.13, and followed your directions to a tee and I am now getting this error.

```
  RAN: '/usr/bin/make -C /Users/mac/touchtracer/kivy-ios/build/hostpython/x86_64/Python-2.7.1 -j8 python Parser/pgen'

  STDOUT:
Makefile:1395: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1396: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1286: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1397: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1398: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1288: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1399: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1289: warning: ignor... (102654 more, please see e.stdout)

  STDERR:
```

**Comment by cruor99** [comment]
Can confirm this worked for me as well.
For those using Buildozer, until it is merged, you simply start as normal until it fails - then edit the files in [project-dir]/.buildozer/ios/platform/kivy-ios/

Also had to include libc++ as @sastels mentioned.

**Comment by mbrockman1** [comment]
Ok, I figured it out and this needs to be put in the docs. I finally was able to build Kivy-iOS. How? I know everyone is dying to know. I reinstalled macOS 10.13 and used APFS case-insensitive filesystem, again do not use case-sensitive APFS!

**Comment by nypgand1** [comment]
Hi, can it be used under Kivy 1.10.1 with Cython 0.25?
(https://kivy.org/docs/installation/installation-linux.html#cython)

**Comment by rogererens** [comment]
When I filter for libz, I get 6 options to choose from.
Can you explain me what to choose?
image

**Comment by mbrockman1** [comment]
Solely the one you highlighted.

**Comment by akshayaurora** [comment]
@tonibagur thanks a ton! 👍

**Comment by Zen-CODE** [comment]
@tonibagur. I'll second that thanks. iOS work is vital but receives way less love + time than Android. This work is much appreciated :-)

**Comment by tonibagur** [comment]
@all, you are wellcome! :)

**Pull request merged**
