### PR TITLE
Fixes to build for Xcode7

### PR DESCRIPTION
**Pull request by jadeblaquiere**
Three significant changes:
1. configure hostpython to build with a version of libffi built for OS X
2. create statically linked hostlibffi to support #1
3. change liblink ld options to signal ld to create an iOS library

### CODE REVIEW

**Comment by jadeblaquiere** [comment]
Incidentally, I've verified this builds using Xcode v6.4 and Xcode v7.1 and I was able to then build and deploy my project from the resulting created projects.

**Comment by BigZaphod** [comment]
I also confirm this works with Xcode 7.1 on OS X 10.11.1.

**Comment by SatoshiMiyazaki** [comment]
Thank you ! Also confirm everything work with with Xcode 7.1 on OS X 10.11.1 as well.
First I tried using tcsh without success but switching to bash makes things work.

**Comment by D-Cipher** [comment]
Hey guys,

Tried with xcode 7 and 6.4, but I'm getting this error:
ld: warning: directory not found for option '-F/Users/tingbochen/kivy-ios/dist/frameworks'
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame

Any ideas?

**Comment by jadeblaquiere** [comment]
I also get the "directory not found" warning... but it seems to be non-fatal. That warning shows up regardless of whether this patch is applied or not and for both Xcode 6 and Xcode 7.

I have not seen the "could not create compact unwind" warning in my testing.

**Comment by D-Cipher** [comment]
Thanks jadeblaquiere, I figured it out. 

I posted a guide to the build detailing some of the stumbling blocks I found here:
https://goo.gl/swR2L5

**Comment by tito** [comment]
Thanks you!

**Comment by orangeseki** [comment]
I cannot get Kivy to work with El Capitan. When trying to run helloapp.py I get this error message in Terminal:

Last login: Mon Nov 23 00:49:47 on ttys001
hashmy-mac:test files omar$ python helloApp.py
[INFO   ] [Logger      ] Record log in /Users/omar/.kivy/logs/kivy_15-11-23_1.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Text        ] Unable to find any valuable Text provider at all!
sdl2 - ImportError: dlopen(/Library/Python/2.7/site-packages/kivy/core/text/_text_sdl2.so, 2): Library not loaded: @executable_path/../Frameworks/SDL2.framework/Versions/A/SDL2
  Referenced from: /Library/Python/2.7/site-packages/kivy/core/text/_text_sdl2.so
  Reason: unsafe use of @executable_path in /Library/Python/2.7/site-packages/kivy/core/text/_text_sdl2.so with restricted binary
  File "/Library/Python/2.7/site-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Library/Python/2.7/site-packages/kivy/core/text/text_sdl2.py", line 12, in <module>
    from kivy.core.text._text_sdl2 import (_SurfaceContainer, _get_extents,

pil - ImportError: dlopen(/Library/Python/2.7/site-packages/PIL/_imaging.so, 2): Library not loaded: /opt/local/lib/libz.1.dylib
  Referenced from: /Library/Python/2.7/site-packages/PIL/_imaging.so
  Reason: image not found
  File "/Library/Python/2.7/site-packages/kivy/core/__init__.py", line 57, in core_select_lib
    fromlist=[modulename], level=0)
  File "/Library/Python/2.7/site-packages/kivy/core/text/text_pil.py", line 8, in <module>
    from PIL import Image, ImageFont, ImageDraw
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 63, in <module>
    from PIL import _imaging as core

[CRITICAL] [App         ] Unable to get a Text provider, abort.


Please help!

**Comment by akshayaurora** [comment]
@orangeseki this issue is about iOS not OS X. for  your issue on OsX either disable SIP(google disabling sip) or use a virtualenv. I recommend using a virtualenv. Disabling sip does not seem like a wise/long term solution.

**Comment by akshayaurora** [comment]
for the issue with OS X We have included a fix in kivy itself, no need for disabling SIP or to use a virtualenv.

**Comment by jmercouris** [comment]
Is this confirmed as working with Xcode 7.2.1?

**Pull request merged**
