### PR TITLE
Fix Module/Name Not Found errors

### PR DESCRIPTION
**Pull request by hackalog**
Not sure what is causing it, but the hostpython-compiled pyo files don't seem to do the trick for anything but main.py. Imports are failing with `No module named XXX` or "Name Not Found"
(see, e.g. #334)

EDIT: the cause was a missing PYTHONOPTIMIZE=2 (-OO). See https://bugs.python.org/issue12982 for the reason

### CODE REVIEW

**Comment by tito** [comment]
Nop. Which python version? 3 on your test maybe?
Cause compileall on python2 is ok, but now i just think that for Python 3, the compileall must be fixed to use the `  -b                    use legacy (pre-PEP3147) compiled file locations`

**Comment by tito** [comment]
I may have missed to do it, and adapt the pbxproj manually when testing both before.

**Comment by tito** [comment]
And yes, on Python 2, py+pyc can be removed to have only pyo; on Python 3, py+pyo can be removed to have only pyc (pyo is no more)

**Comment by hackalog** [comment]
`compileall` is definitely failing for me with python2. (and presumably, for @hoangvuche too, as this PR fixed the issue here: https://github.com/kivy/kivy-ios/issues/334)

 main.pyo loads just fine, but none of the other pyo files can be imported unless the .py files are present.

**Comment by hackalog** [comment]
Having a look around, I noticed this old python issue:
   https://bugs.python.org/issue12982

which indicates that importing from .pyo files only works if python is run with the -O option

Would changing https://github.com/kivy/kivy-ios/blob/49c607a80d2094364ede55c08a8c3d1c01fa3653/tools/templates/%7B%7B%20cookiecutter.project_name%20%7D%7D-ios/main.m#L100 maybe using ` PyRun_SimpleFileExFlags` to run with the -O flag set do the trick, I wonder?

**Comment by tito** [comment]
I removed the PYTHONOPTIMIZATION env for an unknown reason at https://github.com/kivy/kivy-ios/commit/9ad9abf9b605f15793223b700db0eb65c57a9b24#diff-0fd9b1b9cb0b2208eb9ec7f645ba4402

Try to add it again, if it works, just commit it

**Comment by hackalog** [comment]
That was it. This is good to merge @tito

**Pull request merged**
