### PR TITLE
Improve building robust

### PR DESCRIPTION
**Pull request by Michael-X-Net**
+ clean up folder before building.
+ auto create building folder 
+ extract before building.

### CODE REVIEW

**Comment by AndreMiras** [comment]
Thanks for the pull request @Michael-X-Net.
Did you have a build issue that this change fixes?

**Comment by misl6** [comment]
Hi @Michael-X-Net !

Can you please add a description related to all the changes?
I've seen you've added a recipe for `boringssl`, is that related to your first commit?

**Comment by Michael-X-Net** [comment]
@misl6 
Sorry, I forget this pull still open.
The receipt for boringssl is not related to the previous commit.

@AndreMiras 
Sorry I missed the notice email on July.
I found some issue when I try to rebuild after change, so I added the clean up process.

Sorry this pull have mixing several changes now.
If this is not good to merge please close it.

**Comment by misl6** [comment]
Do you still recall what was the issue you were encountering?
Can you split this PR into different ones, as are targeting multiple features / issues ?

**Comment by Michael-X-Net** [comment]
@misl6 
Good thinking.
I will close this pull first.
Thank you all your feedback.

**Pull request closed without merging**
