### PR TITLE
Moving to dedicated kivy_ios/ package directory

### PR DESCRIPTION
**Pull request by AndreMiras**
- updates all imports to prefix kivy_ios
- adds basic `setup.py` file
- adds a simple `toolchain.py` to the root folder for compat

Makes it possible to install kivy-ios from PyPI:
```
pip install kivy-ios
toolchain --help
```
Note the `rebuild_updated_recipes.py` is expected to fail as we
moved all the recipes.

This is a working, but unperfect iteration that come with limitations
we would address in subsequent pull requests, such as:
- [x] ~build/, dist/ and other files get created on `site-packages/`~
- [ ] CI is not testing the source distribution creation and install
- [ ] Continuous Delivery to PyPI is not in place
- [ ] the new usage is not yet documented
- [ ] `toolchain` binary is a bit too generic name
- [ ] we're still vendoring things under `tools/`

### CODE REVIEW

**Comment by AndreMiras** [comment]
I'm sorry for the giant ass PR, but when you look into it I've simply moved files to the `kivy_ios/` package and also sneaked some minor changes needed to make it work.
What I would suggest reviewer to focus on is to see if I didn't break the existing workflow too much which is to have build working after doing a `git clone`.
If this is still working, then any iteration going through a working pip package is a win. I would say this first iteration would get us close to a 90%.
I've already published a version that reflects this PR so you can give it a try with:
```
pip install kivy-ios
# then use with:
toolchain --help
```

**Comment by misl6** [comment]
Tested via:
```
virtualenv -p python3.7 venv
source venv/bin/activate
pip install -r requirements.txt
python toolchain.py build python3 kivy
python toolchain.py create Touchtracer ...
open touchtracer-ios/touchtracer.xcodeproj
```
Worked flawlessly.

**Comment by Zen-CODE** [comment]
@AndreMiras The git clone does not work out of the box" as it gives the error (as expected):
```
ModuleNotFoundError: No module named 'sh'
```
Once you install the requirements, it works fine! And I'm totally okay with that. I think removing these as included modules is the absolutely the right approach, and having a `venv`  or pip install is really a better practice anyhow. 

But I see it still includes the `tools/external`? If that's the intention, we need to adjust this line:

   https://github.com/kivy/kivy-ios/blob/b831483cda70ab0885b1706afb95103d12c2cada/toolchain.py#L40

to include `kivy_ios`?

**Comment by AndreMiras** [comment]
Thanks @Zen-CODE, yes the external include is still intentional indeed, we did drop the `sh` and most of the other vendoring but we're still vendoring a few things as I wrote in my commit body. I'd prefer that we address it in subsequent PR or it will be a long running and even more complex PR. Currently we only have very few tools vendored since https://github.com/kivy/kivy-ios/pull/454 was merged.
My plan after we merge this PR, is to have a working (with few vendored) PyPI install. Then it will be my pleasure to delete some more code if I find the way to

**Pull request merged**
