### PR TITLE
build ffpyplayer version 3.2 instead of master

### PR DESCRIPTION
**Pull request by cbenhagen**

### CODE REVIEW

**Comment by tito** [comment]
Hi, why ? :)

**Comment by cbenhagen** [comment]
Hi :) I feel it is always better to install a released version instead of master. Just in case master gets unstable at some point. Or introduces changes that break stuff on ios.

**Comment by cbenhagen** [comment]
Current master does not build. Using releases instead of development branches just seems like a sane way to prevent such problems.

**Comment by schitzN** [comment]
I can not built ffpyplayer master too and changed the recipe to v3.2, which does work, but my kivy-ios xcode-project is telling me now that there are linker-errors without further informations.

Does this workaround with changing the recipe to v3.2 work for you?

**Comment by cbenhagen** [comment]
Yes this worked for me.

**Comment by schitzN** [comment]
@cbenhagen so you simply changed the recipe to v3.2 and build kivy and ffpyplayer with the current toolchain? which osx/xcode version do you use? everything works fine for me, i already built kivy-ios apps successfully, but as soon as i build ffpyplayer with the toolchain, i get this "linker command failed" in xcode... :/

**Comment by cbenhagen** [comment]
I am using OS X 10.11.3 and Xcode 7.2.1. Maybe I should mention that I am using buildozer to build my iOS Projects.

Can you provide the error logs? Have you tried to rebuild the whole toolchain?

**Comment by schitzN** [comment]
Here is my xcode-error output: http://pastebin.com/LuLfeKiZ

yes, i did rebuild the whole toolchain, multiple times!
I did ./toolchain.py clean and ./toolchain.py distclean
and then build everything with ./toolchain.py build openssl ffpyplayer kivy

I also updated my app with ./toolchain.py update and even completely deleted the project and created a new one with ./toolchain.py create .......

Before i built the toolchain with ./toolchain.py build openssl kivy and everything worked fine!

So buildozer is working for ios?
On their github-page they write: ios                iOS target, based on kivy-ios project. (not working yet.)
so i thought it's not working...

**Comment by cbenhagen** [comment]
It is working most of the time. Make sure to apply this patch https://github.com/kivy/buildozer/commit/72b2039d7606bff87be471a181afe11ec0a7bcd5 or use buildozer master.

**Comment by cbenhagen** [comment]
@tito any news on this? Building master is still broken. While we might find a way to build it, there is no guarantee that it will still build in a month.

**Comment by Zen-CODE** [comment]
Must say, I second this. Most of the recipes pull a stable, tested version. That seems entirely sensible and avoids breaking things unpredictably.

**Pull request merged**
