### PR TITLE
add `flask` and `flask` depend recipes.

### PR DESCRIPTION
**Pull request by lc-soft**

### CODE REVIEW

**Comment by Zen-CODE** [comment]
Would like to merge this, but need a test. Do you have a minimal kivy flask app I could test with? Thanks

**Comment by lc-soft** [comment]
@Zen-CODE 
Sorry, I can not provide minimal kivy flask app, because this is part of the work project at a long time ago , but now I do not have doing this work.

**Comment by Zen-CODE** [comment]
Try to build, I get the following error:

https://gist.github.com/Zen-CODE/0259c5703f415822df0671130f675936

I know you said that you are no longer working on this, so it's hard to fix. None the less, I post the error log for the sake of completeness.

**Comment by lc-soft** [comment]
@Zen-CODE 
ok, I'll set up Mac OS environment to test it.

**Comment by Zen-CODE** [comment]
Thanks. It's appreciated. This would be a nice addition and I'd love to merge it if we can get it working.

**Comment by lc-soft** [comment]
@Zen-CODE 
Now, you can try build it agian.

**Comment by Zen-CODE** [comment]
@lc-soft. Thanks. Will test tomorrow.

**Comment by Zen-CODE** [comment]
Great stuff. Thanks

**Pull request merged**
